[manifest]
version = "1.0.0"
dump_lua = true
priority = 2147483647

# fix 'en' appearing before text
[[patches]]
[patches.pattern]
target = "lib/loc.lua"
pattern = "local outstr = loc.lang .. \".\"..s"
position = "at"
payload = "local outstr = s"
match_indent = true